apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AbdulrasheedApampa/Interview-Task-ACRPS.git
    targetRevision: main
    path: k8s-manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
