apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.5
    chart: promtail
    helm:
      values: |
        config:
          server:
            log_level: info
            http_listen_port: 9080
          positions:
            filename: /run/promtail/positions.yaml
          clients:
            - url: http://lgtm-stack-loki-distributor.monitoring.svc.cluster.local:3100/loki/api/v1/push
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_name]
                  action: replace
                  target_label: job
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod
        serviceAccount:
          create: true
        extraVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: containers
            hostPath:
              path: /var/lib/docker/containers
        extraVolumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: containers
            mountPath: /var/lib/docker/containers
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
