apiVersion: v1
kind: Secret
metadata:
  name: loki-basic-auth
  namespace: monitoring
type: Opaque
data:
  auth: dXNlcjokMnkkMTAkSExnZ1BXZldFK1FRL29tL2FtVmVrdS5RdDdKL2ZGQUZCUHNrcW9KbDIzLjVwc0VXUmdNZWVl # user:password
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: loki-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Loki'
spec:
  rules:
  - host: loki.YOUR_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki-gateway
            port:
              number: 80
