apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring
data:
  values.yaml: |
    loki:
      storage:
        type: gcs
        gcs:
          bucket_name: dru-interview-one-loki-storage
      
    gateway:
      enabled: true
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: loki.YOUR_DOMAIN
            paths:
              - path: /
                pathType: Prefix
        auth:
          enabled: true
