apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-values
  namespace: monitoring
data:
  values.yaml: |
    mimir:
      structuredConfig:
        common:
          storage:
            backend: gcs
            gcs:
              bucket_name: YOUR_PROJECT_ID-mimir-storage
        blocks_storage:
          gcs:
            bucket_name: YOUR_PROJECT_ID-mimir-storage
        ruler_storage:
          gcs:
            bucket_name: YOUR_PROJECT_ID-mimir-storage
        alertmanager_storage:
          gcs:
            bucket_name: YOUR_PROJECT_ID-mimir-storage

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: mimir.YOUR_DOMAIN
          paths:
            - path: /
              pathType: Prefix
